# Generated by ariadne-codegen
# Source: graphql/operations/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateUser(BaseModel):
    create_user: "CreateUserCreateUser" = Field(alias="createUser")


class CreateUserCreateUser(BaseModel):
    id: int
    todos: list["CreateUserCreateUserTodos"]
    email: str
    name: str
    picture: Optional[str]
    provider: str


class CreateUserCreateUserTodos(BaseModel):
    id: int
    title: str
    description: str
    completed: bool


CreateUser.model_rebuild()
CreateUserCreateUser.model_rebuild()
