# Generated by ariadne-codegen
# Source: graphql/client-schema.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateTodoInput(BaseModel):
    title: str
    owner_id: int = Field(alias="ownerId")
    description: str = ""


class CreateUserInput(BaseModel):
    email: str
    name: str
    picture: Optional[str] = None
    provider: str = "local"


class UpdateTodoInput(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    completed: Optional[bool] = None
