# Generated by ariadne-codegen
# Source: graphql/operations/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateTodo(BaseModel):
    update_todo: Optional["UpdateTodoUpdateTodo"] = Field(alias="updateTodo")


class UpdateTodoUpdateTodo(BaseModel):
    id: int
    title: str
    description: str
    completed: bool
    owner: "UpdateTodoUpdateTodoOwner"


class UpdateTodoUpdateTodoOwner(BaseModel):
    id: int
    email: str
    name: str
    picture: Optional[str]
    provider: str


UpdateTodo.model_rebuild()
UpdateTodoUpdateTodo.model_rebuild()
