# Generated by ariadne-codegen
# Source: graphql/operations/

from typing import Optional

from .base_model import BaseModel


class Users(BaseModel):
    users: list["UsersUsers"]


class UsersUsers(BaseModel):
    id: int
    todos: list["UsersUsersTodos"]
    email: str
    name: str
    picture: Optional[str]
    provider: str


class UsersUsersTodos(BaseModel):
    id: int
    title: str
    description: str
    completed: bool


Users.model_rebuild()
UsersUsers.model_rebuild()
