# Generated by ariadne-codegen
# Source: graphql/operations/

from typing import Any, Optional, Union

from .base_client import BaseClient
from .base_model import UNSET, UnsetType
from .create_todo import CreateTodo
from .create_user import CreateUser
from .delete_todo import DeleteTodo
from .input_types import CreateTodoInput, CreateUserInput, UpdateTodoInput
from .todo import Todo
from .todos import Todos
from .update_todo import UpdateTodo
from .user import User
from .users import Users


def gql(q: str) -> str:
    return q


class SupergraphClient(BaseClient):
    def create_todo(self, input: CreateTodoInput, **kwargs: Any) -> CreateTodo:
        query = gql("""
            mutation CreateTodo($input: CreateTodoInput!) {
              createTodo(input: $input) {
                id
                title
                description
                completed
                owner {
                  id
                  email
                  name
                  picture
                  provider
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="CreateTodo", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateTodo.model_validate(data)

    def update_todo(self, id: int, input: UpdateTodoInput, **kwargs: Any) -> UpdateTodo:
        query = gql("""
            mutation UpdateTodo($id: Int!, $input: UpdateTodoInput!) {
              updateTodo(id: $id, input: $input) {
                id
                title
                description
                completed
                owner {
                  id
                  email
                  name
                  picture
                  provider
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = self.execute(
            query=query, operation_name="UpdateTodo", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateTodo.model_validate(data)

    def delete_todo(self, id: int, **kwargs: Any) -> DeleteTodo:
        query = gql("""
            mutation DeleteTodo($id: Int!) {
              deleteTodo(id: $id)
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query, operation_name="DeleteTodo", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DeleteTodo.model_validate(data)

    def create_user(self, input: CreateUserInput, **kwargs: Any) -> CreateUser:
        query = gql("""
            mutation CreateUser($input: CreateUserInput!) {
              createUser(input: $input) {
                id
                todos {
                  id
                  title
                  description
                  completed
                }
                email
                name
                picture
                provider
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="CreateUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateUser.model_validate(data)

    def todos(
        self, owner_id: Union[Optional[int], UnsetType] = UNSET, **kwargs: Any
    ) -> Todos:
        query = gql("""
            query Todos($ownerId: Int) {
              todos(ownerId: $ownerId) {
                id
                title
                description
                completed
                owner {
                  id
                  email
                  name
                  picture
                  provider
                }
              }
            }
            """)
        variables: dict[str, object] = {"ownerId": owner_id}
        response = self.execute(
            query=query, operation_name="Todos", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Todos.model_validate(data)

    def todo(self, id: int, **kwargs: Any) -> Todo:
        query = gql("""
            query Todo($id: Int!) {
              todo(id: $id) {
                id
                title
                description
                completed
                owner {
                  id
                  email
                  name
                  picture
                  provider
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query, operation_name="Todo", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Todo.model_validate(data)

    def users(self, **kwargs: Any) -> Users:
        query = gql("""
            query Users {
              users {
                id
                todos {
                  id
                  title
                  description
                  completed
                }
                email
                name
                picture
                provider
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="Users", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Users.model_validate(data)

    def user(self, id: int, **kwargs: Any) -> User:
        query = gql("""
            query User($id: Int!) {
              user(id: $id) {
                id
                todos {
                  id
                  title
                  description
                  completed
                }
                email
                name
                picture
                provider
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query, operation_name="User", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return User.model_validate(data)
