# Generated by ariadne-codegen
# Source: graphql/operations/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateTodo(BaseModel):
    create_todo: "CreateTodoCreateTodo" = Field(alias="createTodo")


class CreateTodoCreateTodo(BaseModel):
    id: int
    title: str
    description: str
    completed: bool
    owner: "CreateTodoCreateTodoOwner"


class CreateTodoCreateTodoOwner(BaseModel):
    id: int
    email: str
    name: str
    picture: Optional[str]
    provider: str


CreateTodo.model_rebuild()
CreateTodoCreateTodo.model_rebuild()
