# Generated by ariadne-codegen
# Source: graphql/operations/

from pydantic import Field

from .base_model import BaseModel


class DeleteTodo(BaseModel):
    delete_todo: bool = Field(alias="deleteTodo")
