# Generated by ariadne-codegen
# Source: graphql/operations/

from typing import Optional

from .base_model import BaseModel


class Todo(BaseModel):
    todo: Optional["TodoTodo"]


class TodoTodo(BaseModel):
    id: int
    title: str
    description: str
    completed: bool
    owner: "TodoTodoOwner"


class TodoTodoOwner(BaseModel):
    id: int
    email: str
    name: str
    picture: Optional[str]
    provider: str


Todo.model_rebuild()
TodoTodo.model_rebuild()
