# Generated by ariadne-codegen
# Source: graphql/operations/

from typing import Optional

from .base_model import BaseModel


class Todos(BaseModel):
    todos: list["TodosTodos"]


class TodosTodos(BaseModel):
    id: int
    title: str
    description: str
    completed: bool
    owner: "TodosTodosOwner"


class TodosTodosOwner(BaseModel):
    id: int
    email: str
    name: str
    picture: Optional[str]
    provider: str


Todos.model_rebuild()
TodosTodos.model_rebuild()
