# Generated by ariadne-codegen
# Source: graphql/operations/

from typing import Optional

from .base_model import BaseModel


class User(BaseModel):
    user: Optional["UserUser"]


class UserUser(BaseModel):
    id: int
    todos: list["UserUserTodos"]
    email: str
    name: str
    picture: Optional[str]
    provider: str


class UserUserTodos(BaseModel):
    id: int
    title: str
    description: str
    completed: bool


User.model_rebuild()
UserUser.model_rebuild()
